name: Docker registry

on:
   push:
     tags:
       - 'v*'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :tag
        if: success()
        run: docker build -t aoirint/vbam:${IMAGE_TAG} .

      - name: Build :latest
        if: success()
        run: docker build -t aoirint/vbam:latest .

      - name: Build :ubuntu-tag
        if: success()
        run: docker build . -t aoirint/vbam:ubuntu-${IMAGE_TAG} --build-arg "BASE_IMAGE=ubuntu:bionic"

      - name: Build :ubuntu
        if: success()
        run: docker build . -t aoirint/vbam:ubuntu --build-arg "BASE_IMAGE=ubuntu:bionic"

      - name: Build :nvidia-tag
        if: success()
        run: docker build . -t aoirint/vbam:nvidia-${IMAGE_TAG} --build-arg "BASE_IMAGE=nvidia/opengl:base-ubuntu18.04"

      - name: Build :nvidia
        if: success()
        run: docker build . -t aoirint/vbam:nvidia --build-arg "BASE_IMAGE=nvidia/opengl:base-ubuntu18.04"


      - name: Deploy :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:${IMAGE_TAG}

      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:latest

      - name: Deploy :ubuntu-tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:ubuntu-${IMAGE_TAG}

      - name: Deploy :ubuntu
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:ubuntu

      - name: Deploy :nvidia-tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:nvidia-${IMAGE_TAG}

      - name: Deploy :nvidia
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/vbam:nvidia



      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
